feat: use TOML config
catppuccin/alacritty pull request #21
Opened 2023-06-22 17:02 UTC by nekowinston

Closes #20.

This should be merged whenever Alacritty releases a version that includes https://github.com/alacritty/alacritty/commit/bd4906722a1a026b01f06c94c33b13ff63a7e044.

We don't need to keep the YAML files in the repo, as we can simply link to an older revision of this repo if people want to have a look at the YAML formats.

2023-06-26 14:14 UTC, nekowinston commented
I'll add a

> # Usage
> **Note**
> If you're using Alacritty <`next Alacritty version`, please look at the [YAML tag](#yaml-tag)

after merging this.

2023-07-10 15:00 UTC, gersonsosa requested changes

2023-07-10 15:00 UTC, gersonsosa commented on README.md
> +  "~/.config/alacritty/catppuccin/catppuccin-mocha.yml"
this should end with .toml

2023-07-10 15:11 UTC, nekowinston commented on README.md
> +  "~/.config/alacritty/catppuccin/catppuccin-mocha.yml"
Good catch, thank you.

2023-12-14 04:17 UTC, nekowinston commented
Seems that v0.13 is getting ready for release: https://github.com/alacritty/alacritty/releases/tag/v0.13.0-rc1

2023-12-28 06:54 UTC, merged